language: d
sudo: false

matrix:
    include:
        - d: dmd
        - d: dmd-2.078.2
        - d: dmd-2.077.1
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: dmd-2.073.1
        - d: dmd-2.073.0
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.071.0
        - d: dmd-2.070.2
        - d: dmd-2.070.1
        - d: dmd-2.070.0
        - d: dmd-2.069.2
        - d: dmd-2.069.0
        - d: ldc
        - d: ldc-1.0.0
        # Latest GDC (v5.2.0) uses a too-old DMDFE (2.066), so
        # it won't work on current SDLang-D. So it's set as
        # an allowed failure for travis.
        - d: gdc
    allow_failures:
        - d: gdc
