language: d
sudo: false

matrix:
    include:
        - d: dmd-2.081.1
        - d: dmd-2.080.1
        - d: dmd-2.079.1
        - d: dmd-2.078.2
        - d: dmd-2.077.1
        - d: dmd-2.076.1
        - d: dmd-2.075.1
        - d: dmd-2.074.1
        - d: dmd-2.073.1
        - d: dmd-2.073.0
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.071.0
        - d: dmd-2.070.2
        - d: dmd-2.070.1
        - d: dmd-2.070.0
        - d: dmd-2.069.2
        - d: dmd-2.069.0
        - d: ldc-1.9.0
        - d: ldc-1.8.0
        - d: ldc-1.7.0
        - d: ldc-1.6.0
        - d: ldc-1.5.0
        - d: ldc-1.4.0
        - d: ldc-1.3.0
        - d: ldc-1.2.0
        - d: ldc-1.1.1
        - d: ldc-1.0.0
        # Latest GDC (v4.8.5) uses a too-old DMDFE (2.068), so
        # it won't work on current SDLang-D. So it's set as
        # an allowed failure for travis.
        - d: gdc-4.8.5

    allow_failures:
        - d: gdc-4.8.5
