language: d
sudo: false

# At the moment, unit-threaded isn't detecting all all the tests
# (issue: https://github.com/atilaneves/unit-threaded/issues/43)
# so when done, run the tests again using built-in test runner.
script: dub test && dub test --config=unittest-builtin

matrix:
    include:
        - d: dmd
        - d: dmd-2.071.2
        - d: dmd-2.071.0
        - d: dmd-2.070.2
        - d: dmd-2.070.1
        - d: dmd-2.070.0
        - d: dmd-2.069.2
        - d: dmd-2.069.0
        - d: ldc
        - d: ldc-0.17.1
        # Latest GDC (v5.2.0) uses a too-old DMDFE (2.066), so
        # it won't work on current SDLang-D. So it's set as
        # an allowed failure for travis.
        - d: gdc
    allow_failures:
        - d: gdc
